package com.vishal.aiyoutube.topic_management_service.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) representing the final or partial analysis of a topic.
 * This event is produced by the AI Analysis Service and consumed by the Topic Management Service.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AnalysisCompletedEvent {

    /**
     * Unique identifier for the topic being analyzed.
     * Links the analysis results to the correct record in the database.
     */
    private UUID topicId;

    /**
     * The synthesized executive summary generated by the AI.
     * Contains "Partial Analysis for..." during streaming or the final cohesive summary.
     */
    private String finalSummary;

    /**
     * Normalized sentiment score (0.0 to 1.0).
     * Represents the overall public perception extracted from video transcripts.
     */
    private Double sentimentScore;

    /**
     * Percentage value (0 to 100) representing factual agreement across sources.
     * High values indicate that multiple sources confirm the same information.
     */
    private Double consensusPercentage;

    /**
     * A stringified list or description of factual claims found across all analyzed videos.
     */
    private String commonClaims;

    /**
     * A list of specific highlight moments extracted from the analyzed videos.
     * These generate the individual insight cards on the user interface.
     */
    private List<VideoSegmentDTO> segments;

    /**
     * Nested DTO representing a specific highlight moment from a single YouTube video.
     */
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class VideoSegmentDTO {

        /**
         * The unique alphanumeric YouTube Video ID.
         */
        private String videoId;

        /**
         * The title of the YouTube video.
         * Displayed as small metadata above the main insight information.
         */
        private String videoTitle;

        /**
         * The full URL of the video source.
         */
        private String videoUrl;

        /**
         * The specific time location in the video (Format: MM:SS).
         * Used to build the 'Jump to' link for the user.
         */
        private String timestamp;

        /**
         * A detailed contextual explanation of why this specific moment is important.
         */
        private String bestExplanation;

        /**
         * A large, bold headline summary for the specific highlight.
         * Served as the primary information on the Source Highlight card.
         */
        private String segmentSummary;
    }
}
