package com.vishal.aiyoutube.topic_management_service.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import java.util.List;

/**
 * Data Transfer Object (DTO) representing the response payload from the Groq/Grok API.
 * Uses Jackson annotations to safely ignore extra metadata fields not required by the service.
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class GrokChatResponse {

    /**
     * A list of completion results.
     * Usually contains one entry unless the 'n' parameter is specified in the request.
     */
    private List<Choice> choices;

    /**
     * Token statistics for the request.
     * Crucial for monitoring Free Tier usage and preventing Rate Limit (TPD/TPM) errors.
     */
    private Usage usage;

    /**
     * Inner class representing a single completion result.
     */
    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Choice {
        /**
         * The message object containing the actual AI-generated text.
         */
        private Message message;
    }

    /**
     * Inner class representing the content of the AI's response.
     */
    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Message {
        /**
         * The role of the responder, typically "assistant".
         */
        private String role;

        /**
         * The raw text content generated by the LLM (e.g., the 5-6 SEO keywords).
         */
        private String content;
    }

    /**
     * Inner class for tracking token consumption.
     */
    @Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Usage {
        /**
         * Number of tokens in the input prompt.
         */
        private int prompt_tokens;

        /**
         * Number of tokens generated in the response.
         */
        private int completion_tokens;

        /**
         * The sum of prompt and completion tokens.
         */
        private int total_tokens;
    }
}