package com.vishal.aiyoutube.topic_management_service.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.UUID;

/**
 * Data Transfer Object (DTO) representing a successful topic submission.
 * This event is published to Kafka by the Topic Management Service to notify
 * downstream services (like the YouTube Processing Service) to begin work.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TopicSubmittedEvent {

    /**
     * The unique internal database ID for the topic request.
     * Downstream services must include this ID in all subsequent events
     * (Status updates, Analysis results) to maintain data traceability.
     */
    private UUID topicId;

    /**
     * The clean, AI-normalized SEO search string.
     * This is the 5-6 keyword phrase generated by Grok, optimized for
     * retrieving the most relevant YouTube search results.
     */
    private String query;
}