package com.vishal.aiyoutube.topic_management_service.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Main persistent entity representing a research topic in the Nexus AI system.
 * This class maps to the 'topics' table and serves as the primary data structure
 * for tracking the lifecycle of an intelligence report.
 */
@Entity
@Table(name = "topics")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TopicEntity {

    /**
     * The primary key for the topic.
     * Uses a UUID strategy to ensure global uniqueness across distributed services.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The original, unformatted input provided by the user.
     * Captured to maintain a record of the user's initial intent.
     */
    @Column(name = "raw_query", nullable = false)
    private String rawQuery;

    /**
     * The clean, SEO-optimized search term generated by the Grok agent.
     * Used for YouTube API searching and internal data deduplication.
     * (e.g., "India Union Budget 2026").
     */
    @Column(name = "normalized_query", columnDefinition = "TEXT")
    private String normalizedQuery;

    /**
     * Current state of the topic in the processing pipeline.
     * Persisted as a string for readability in the database.
     * Values: PENDING, EXTRACTING, ANALYZING, COMPLETED, FAILED.
     */
    @Enumerated(EnumType.STRING)
    private TopicStatusEntity status;

    /**
     * Embedded component containing the final high-level AI synthesis.
     * Includes the Executive Summary, Sentiment, and Consensus metrics.
     */
    @Embedded
    private AnalysisResultEntity analysisResult;

    /**
     * Relationship mapping to specific video highlights identified by AI.
     * One Topic can have multiple Video Insights.
     * CascadeType.ALL ensures insights are saved/deleted with the topic.
     */
    @OneToMany(mappedBy = "topic", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<VideoInsightEntity> videoInsights;

    /**
     * Automatic timestamp indicating when the request was first created.
     */
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Automatic timestamp that updates every time the topic status or result changes.
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}